apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1
suites:
  - name: Amtrak Tests
    workload: webdriver
    image: leyfr01/so-demo-java:0.0.3
    # the command to run your tests
    entrypoint: mvn clean test
    artifacts:
      - "/workdir/CZI-Demo/target/surefire-reports/*"

artifacts:
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts